# Generated by Django 5.2.13 on 2026-05-02 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('period_date', models.DateField(db_index=True)),
                ('account_no', models.CharField(max_length=20)),
                ('source_pdf_name', models.CharField(max_length=255)),
                ('parsed_at', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dividend_income', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('realized_pnl_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alpaca_raw', models.JSONField()),
                ('markowitz_raw', models.JSONField(blank=True, null=True)),
                ('semaforo_raw', models.JSONField(blank=True, null=True)),
                ('advisor_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_date'],
                'unique_together': {('account_no', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.monthlysnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('side', models.CharField(max_length=10)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.monthlysnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=16)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pnl_pct', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sharpe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.monthlysnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'symbol')},
            },
        ),
    ]
