# Generated by Django 5.2.13 on 2026-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_dividendconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendconfig',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
