# Generated by Django 5.2.13 on 2026-05-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_dividendconfig_tax_exempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemaphoreRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('semaforo_raw', models.JSONField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaphore_runs', to='portfolio.monthlysnapshot')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
