# Generated by Django 5.2.13 on 2026-05-02 16:06

from django.db import migrations


def migrate_semaforo_raw(apps, schema_editor):
    MonthlySnapshot = apps.get_model("portfolio", "MonthlySnapshot")
    SemaphoreRun = apps.get_model("portfolio", "SemaphoreRun")
    for snapshot in MonthlySnapshot.objects.exclude(semaforo_raw__isnull=True):
        SemaphoreRun.objects.create(
            snapshot=snapshot,
            semaforo_raw=snapshot.semaforo_raw,
            ran_at=snapshot.parsed_at,
        )


def reverse_migrate(apps, schema_editor):
    SemaphoreRun = apps.get_model("portfolio", "SemaphoreRun")
    SemaphoreRun.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_semaphorerun'),
    ]

    operations = [
        migrations.RunPython(migrate_semaforo_raw, reverse_migrate),
    ]
